# Generated by Django 4.0.3 on 2022-06-14 17:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_books_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField(default=datetime.timedelta(days=5))),
                ('status', models.CharField(choices=[('orderplaced', 'orderplaced'), ('dispatch', 'dispatch'), ('in_transit', 'in_transit'), ('delivered', 'delivered'), ('order_cancelled', 'order_cancelled')], default='order_placed', max_length=120)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
